### ISSUE TITLE
Auto-lock and auto-logout times not sticking

### ISSUE THREAD

**Issue by BinaryPop** [vanowm/MasterPasswordPlus#130]
Hi,

This is a great extension for Firefox. However, there does appear to be a small issue with it (unless I'm doing something wrong): the auto-lock and auto-logout time settings are not retained, but revert back to their default 5 mins when the settings pages are reloaded. So, for example, if I try to set the auto-lock time to 1 hour and click OK, when I reload the settings it shows up as 5 mins. And my 1 hour setting has not taken effect because, sure enough, 5 mins later the browser is locked. Other settings in these tabs appear to work fine (although I haven't tested them all).

Would you be able to fix this, please, so that the configured timeout settings take effect?

Thanks!

**Comment by vanowm** [comment]
This issue was fixed in v1.26 (I forgot add it in changes log), which was submitted to mozilla for signature August 12...still waiting, it's 27th of 176 in the queue now.

Before I close this issue, would you confirm that Startup -> auto-logout setting saves properly?
In the meantime, you can set it manually via (type in address bar, numbers are in seconds):
**about:config?filter=extensions.masterPasswordPlus.logouttimeout** for Auto-logout
and
**about:config?filter=extensions.masterPasswordPlus.locktimeout** for Auto-Lock

**Comment by BinaryPop** [comment]
Thanks for your quick response. Your manual workarounds work a treat - thanks! And the Startup->Auto-logout setting does appear to save properly.

One more thing: it would be a great enhancement if the master password had to be re-entered before any of these additional settings could be changed.

**Comment by vanowm** [comment]
That is a good idea, at least when protect options is enabled. If you would start another issue regarding this please.
