### ISSUE TITLE
Pale Moon port?

### ISSUE THREAD

**Issue by luciph0r** [vanowm/MasterPasswordPlus#155]
Would you consider porting this to [Pale Moon](https://www.palemoon.org)? I found it in the Classic Addons Archive, and saw the note there that it will never work on Firefox 57+.
I've installed it on PM and it works fine, you would only have to add the Pale Moon application ID in install.rdf for it to work seamlessly, like so - 
`    <em:targetApplication><!-- Pale Moon -->`
			`<Description>`
`				<em:id>{8de7fcbb-c55c-4fbe-bfc5-fc555c87dbc4}</em:id>`
`				<em:minVersion>28.0</em:minVersion>`
`				<em:maxVersion>28.*</em:maxVersion>`
`		         </Description>`
`		</em:targetApplication>`

**Comment by vanowm** [comment]
Pale Moon support was added back in v1.24 two years ago ;)

It seem recently they added developer page, were new addons can be submitted and managed (last time I checked we had to email them the addons)...

I just tried submitting it, but it [refused](https://forum.palemoon.org/viewtopic.php?f=44&t=22918) it, because addon used to be listed on mozilla's website...

**Comment by luciph0r** [comment]
Thank you so much! I just looked at the thread. They will be able to publish it soon. Given how Mozilla shot itself in the foot by getting rid of XUL/XPCOM, this is the only browser left for power users who miss such features. I have been looking through the classic addons site for powerful addons like yours and trying to get people on board here :)

**Comment by vanowm** [comment]
Published
https://addons.palemoon.org/addon/master-password/
